server:
  port: 10080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.82.129:3306/hotel
    username: hotel
    password: pC2TTWCjFT7Rkxyf